### ISSUE TITLE
Motivation?

### ISSUE THREAD

**Issue by dumblob** [BenStigsen/vgui#1]
Just curious - why do you develop your own GUI lib?

There is `vui` (far from optimal which it'll never be due to its archaic architecture focused solely on "layout at startup", but it gets the job done). If you are looking for an immediate mode lib, then there are plenty good ones (e.g. I am one of the maintainers of [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear )).

I am really interested what is your motivation :wink:. Is it just for study purposes?

Cheers!

**Comment by BenStigsen** [comment]
Thank you for the question, it's a good one.

`vui` has great potential and I think it'll be very useful once stable. But I personally am not a fan of how hard it is, to avoid the layout system. I like being able to place elements using absolute position and this is not easy with `vui`.

To me `vui` provides way more functionality than I need. Excluding `webview/` and `examples/`, the `vui` directory contains 12600+ lines of V code. `vgui` as of writing this (also excluding `examples/`) only contains 980+ lines of code. In other words, currently `vgui` is about 92% smaller. I also have a feeling that due to all of this, especially when making use of `gg.ui_mode` and more, `vgui` will be faster than `vui`.

I am aware that there are immediate mode libraries out there, I have also used Nuklear before. But I wanted to make a GUI library in V, that does not depend on other C libraries than `sokol`.

The goal of `vgui` is provide an alternative to `vui` that's small and very easy to use. Highly inspired by [raygui](https://github.com/raysan5/raygui).

**Comment by dumblob** [comment]
Interesting - my thoughts wander in about the same direction :wink:.

It actually makes sense assuming you have enough time to develop your own lib.

Btw. I know raygui and it's a good library. I assume you didn't just wrap it for use in *V* for the same reason you're not using `vui` - namely its size :wink:.

**Comment by BenStigsen** [comment]
No, I didn't wrap raygui just because I wanted to create something directly with V, using the V graphics backend `gg`.

**Comment by dumblob** [comment]
Ok, I'll follow your development to see how far you come - I'm myself a fan of GUI libs (yeah, I admit I'm a freak), so this is yet another fresh meat for me :wink:.
